### PR TITLE
per user lock file

### PR DESCRIPTION
**Pull request by jstkdng**
use user's cache dir instead of /tmp

### CODE REVIEW

**Comment by gokberkgunes** [comment]
I am not confident that I understand why one would like to use cache folder instead of the /tmp. Can you please elaborate?

What comes to my mind is that having an environmental variable for ueberzug's cache folder instead of changing /tmp, if this is not set we may fallback to /tmp.

Lastly, the implementation is assuming .cache is set at home directory. Instead of directly assuming cache directory is at home, can we instead use `$XDG_CACHE_HOME` and if it does not exists fallback to /tmp?

**Comment by jstkdng** [comment]
Using /tmp doesn't work when there's two users logged in at the same time in one computer. In this case, the first user to run ranger with ueberzug will be the only one able to use view images in the terminal. When the second user tries to use ranger with ueberzug, ueberzug will try to create the same lock in /tmp but it will not be able to because the lock file already exists and belongs to the first user.

**Comment by gokberkgunes** [comment]
Alright, I could replicate the issue with tmux multiple users logged in. The only problem right now is that we're assuming cache directory is set at home. To prevent this, can you change the commit something like below?
```python
xdg_cache_dir = os.environ.get("XDG_CACHE_HOME")

if (xdg_cache_dir):
    lock_directory_path = pathlib.PosixPath(xdg_cache_dir) / "ueberzug"
else:
    lock_directory_path = pathlib.PosixPath.joinpath(pathlib.PosixPath.home(),
            pathlib.PosixPath('.cache/ueberzug'))
```

**Comment by jstkdng** [comment]
> Alright, I could replicate the issue with tmux multiple users logged in. 

are you using the tagged 18.1.9 version or master? Seems master lost support for tmux, probably due to the move from python-xlib to libxres.

**Review by gokberkgunes — APPROVED** [review]

**Comment by gokberkgunes** [comment]
I don't know what tagged is, I looked it up online but no results. Generally, I do not use tmux at all, I installed it to replicate the bug.

**Comment by jstkdng** [comment]
I meant this.
image

Are you using the source code up to 18.1.9? or the master branch

**Comment by gokberkgunes** [comment]
I am using master branch. When I tried `tabbed + st + tmux`, there were no previews; `st + tmux` works though. Is this the same on your end? If so, let's open up an issue and discuss it.

**Comment by jstkdng** [comment]
I believe I have fixed it, I'll open a PR

**Pull request merged**
