### PR TITLE
Recursively find window ids

### PR DESCRIPTION
**Pull request by jstkdng**

### CODE REVIEW

**Review by gokberkgunes — COMMENTED** [review]
Is stdio header included but not used?

Works with tmux, dvtm and mtm and when they are in tabbed.

**Review by gokberkgunes — APPROVED** [review]

**Comment by jstkdng** [comment]
Those headers were used for debugging but now are not required.

**Comment by gokberkgunes** [comment]
What provides the calloc and reallocarray, @jstkdng? I searched a while both in the project and online could not find an answer; however, the program compiles just fine without stdlib.

**Comment by jstkdng** [comment]
calloc and reallocarray are defined in the `<stdlib.h>` header. Ideally it should stay there.

> however, the program compiles just fine without stdlib.

[This](https://stackoverflow.com/questions/336814/why-is-include-stdio-h-not-required-to-use-printf) should answer that question. The compiler does some weird things and since the extensions is linked to libc it works fine.

**Pull request merged**
